config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { user: "users/registrations" }

  # root 'jobs#index'
  root 'jobs#index'
  # resources :users # do
    # resources :jobs
  # end

  resources :jobs do
    collection do
      get 'filter'
    end
    resources :steps
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
  has_many :steps
  validates :title, :company, :post_date, :rating, :location, :url, presence: true
  validates :rating, numericality: { only_integer: true }, :inclusion => 1..10

  after_create :add_default_steps

  scope :most_steps, -> (current_user) {(
    select("jobs.id, jobs.title, jobs.company, count(steps.id) as steps_count")
    .where(user_id: current_user.id)
    .joins(:steps)
    .group("jobs.id")
    .order("steps_count DESC")
    .limit(10)
    )}

  scope :fewest_steps, -> (current_user) {(
    select("jobs.id, jobs.title, jobs.company, count(steps.id) as steps_count")
    .where(user_id: current_user.id)
    .joins(:steps)
    .group("jobs.id")
    .order("steps_count ASC")
    .limit(10)
    )}

  scope :most_recent, -> (current_user) { order(created_at: :desc).where(user_id: current_user.id).limit(10) }

  private
    def add_default_steps
      default_steps = [
        {description: "LinkedIn Research", notes: "Notes go here (10-250 characters)...", due_date: Faker::Date.forward(10), priority: 1},
        {description: "Write Cover Letter", notes: "Notes go here (10-250 characters)...", due_date: Faker::Date.forward(14), priority: 3},
        {description: "Tailor Résumé", notes: "Notes go here (10-250 characters)...", due_date: Faker::Date.forward(14), priority: 3},
        {description: "Apply", notes: "Notes go here (10-250 characters)...", due_date: Faker::Date.forward(17), priority: 3},
        {description: "Followup", notes: "Notes go here (10-250 characters)...", due_date: Faker::Date.forward(21), priority: 2}
      ]

      default_steps.each do |step|
        self.steps.create(description: step[:description],
                    notes: step[:notes],
                    due_date: step[:due_date],
                    priority: step[:priority])
      end
    end
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :job
  validates :description, :due_date, :priority, presence: true
  validates :notes, length: { in: 10..250 }, allow_blank: true

  after_create :default_status

  def default_status
    self.status = false
    self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :jobs
  has_attached_file :resume
  validates_attachment :resume, content_type: { content_type: "application/pdf" }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :current_password, :resume])
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    if current_user
      @jobs = current_user.jobs
      @new_job = Job.new
    else
      redirect_to :new_user_registration
    end
  end

  def show
    @job = Job.find(params[:id])
    @complete_steps = @job.steps.where(status: true)
    @incomplete_steps = @job.steps.where(status: false)
  end

  def new
    @new_job = Job.new
  end

  def create
    @new_job_to_save = current_user.jobs.new(job_params)
    if @new_job_to_save.save!
      redirect_to jobs_path
    else
      render :new
    end
  end

  def destroy
    Job.find(params[:id]).destroy
    redirect_to jobs_path
  end

  def filter
    # binding.pry
    @new_job = Job.new
    case params[:format]
    when "most"
      @jobs = Job.most_steps(current_user)
    when "fewest"
      @jobs = Job.fewest_steps(current_user)
    when "recent"
      @jobs = Job.most_recent(current_user)
    end
    render :index
  end

private
  def job_params
    params.require(:job).permit(:title, :company, :post_date, :rating, :location, :url)
  end
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def new
    @job = Job.find(params[:job_id])
    @new_step = Step.new
  end

  def create
    @job = Job.find(params[:job_id])
    @new_step = @job.steps.new(step_params)
    if @new_step.save!
      flash[:notice] = "Step successfully added."
      redirect_to job_path(@job)
    else
      flash[:alert] = "There was an error adding this step."
      render :new
    end
  end

  def update
    # binding.pry
    Step.update(params[:id], :status => true) #true is "done"
    redirect_to job_path(Job.find(params[:job_id]))
  end

private
  def step_params
    params.require(:step).permit(:description, :notes, :due_date, :priority)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  # def index
  #   redirect_to jobs_path
  #   # @jobs = current_user.jobs
  # end
  #
  # def show
  #
  # end

  def 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/_form.html.erb
<%= form_for @new_job, html: {class: "form-control-group"} do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
  <%= f.label :company %>
  <%= f.text_field :company, class: 'form-control' %>
  <%= f.label :post_date %>
  <%= f.date_field :post_date, class: 'form-control' %>
  <%= f.label :rating %>
  <%= f.number_field :rating, class: 'form-control' %>
  <%= f.label :location %>
  <%= f.text_field :location, class: 'form-control' %>
  <%= f.label :url %>
  <%= f.text_field :url, class: 'form-control' %>
  <br>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/jobs/index.html.erb
<br>
<% if current_user.resume_file_name != nil  %>
  <a href="<%= current_user.resume.url %>">View your résumé</a>
<% else %>
  No résumé uploaded. Edit profile to add.
<% end %>

<h1>Jobs List:</h1>
<h6>Filter by:</h6>
<%= link_to 'most steps remaining', filter_jobs_path(:most) %> |
<%= link_to 'fewest steps remaining', filter_jobs_path(:fewest) %> |
<%= link_to 'recently added', filter_jobs_path(:recent) %>

<ul class="list-group">
  <% @jobs.each do |job| %>
    <li class="list-group-item"><%= link_to job.title, job_path(job) %>, <%= job.company %></li>
  <% end %>
</ul>
<hr>

<h4>Add a new job:</h4>
<%= render "jobs/form" %>

app/views/jobs/show.html.erb
<br><br>
<button class="btn btn-warning"><%= link_to "Back", jobs_path %></button>
<button class="btn btn-danger"><%= link_to "Remove this job", job_path(@job),
                         :data => {:confirm => "Are you sure?",
                                   :method => "delete"} %></button>

<h1><%= @job.title %></h1>

<div class="card">
  <div class="card-body">
    <h4 class="card-title">Company: <%= @job.company %></h4>
    <h5 class="card-title">Location: <%= @job.location %></h5>
    <p class="card-text"><%= @job.url %></p>
    <p class="card-text">Posting date: <%= @job.post_date %></p>
    <p class="card-text">Your rating: <%= @job.rating %>/10</p>
  </div>
</div>
<hr>
<div class="card">
  <h4>Remaining steps for this job:</h4>
  <div class="card-body">
    <ul class="list-group">
      <% @incomplete_steps.each do |step| %>
        <li class="list-group-item">
          <%= step.description %>
          <%= link_to "mark complete", job_step_path(@job, step), :method => :put %>
        </li>
      <% end %>
    </ul>
    <button type="button" name="button"><%= link_to "Add a step", new_job_step_path(@job)  %></button>
  </div>
</div>

<hr>

<% unless @complete_steps.empty? %>
  <div class="card">
    <h4>Completed steps:</h4>
    <div class="card-body">
      <ul class="list-group">
        <% @complete_steps.each do |step| %>
          <li class="list-group-item">
            <%= step.description %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Job Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <% if current_user %>
        <h4>
            Logged in as: <%= current_user.email %> |
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %> |
            <%= link_to 'Edit Profile', edit_user_registration_path %>
        </h4>
      <% end %>

      <%= flash[:alert] %>
      <%= flash[:notice] %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/steps/_form.html.erb
<%= form_for [@job, @new_step], class:"form-control-group" do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description, class: 'form-control' %>
  <%= f.label :notes %>
  <%= f.text_field :notes, class: 'form-control' %>
  <%= f.label :due_date %>
  <%= f.date_field :due_date, class: 'form-control' %>
  <%= f.label :priority %>
  <%= f.number_field :priority, class: 'form-control' %>
  <br>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/steps/new.html.erb
<h2>Enter a new step for your application to <%= @job.title %></h2>

<%= render 'form' %>